################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/Usuario/Desktop/COPIAS_SEGURIDAD/STM32CubeExpansion_MEMS1_V4.4.1/Drivers/BSP/Components/hts221/HTS221_Driver.c \
C:/Users/Usuario/Desktop/COPIAS_SEGURIDAD/STM32CubeExpansion_MEMS1_V4.4.1/Drivers/BSP/Components/hts221/HTS221_Driver_HL.c \
C:/Users/Usuario/Desktop/COPIAS_SEGURIDAD/STM32CubeExpansion_MEMS1_V4.4.1/Drivers/BSP/Components/lis3mdl/LIS3MDL_MAG_driver.c \
C:/Users/Usuario/Desktop/COPIAS_SEGURIDAD/STM32CubeExpansion_MEMS1_V4.4.1/Drivers/BSP/Components/lis3mdl/LIS3MDL_MAG_driver_HL.c \
C:/Users/Usuario/Desktop/COPIAS_SEGURIDAD/STM32CubeExpansion_MEMS1_V4.4.1/Drivers/BSP/Components/lps22hb/LPS22HB_Driver.c \
C:/Users/Usuario/Desktop/COPIAS_SEGURIDAD/STM32CubeExpansion_MEMS1_V4.4.1/Drivers/BSP/Components/lps22hb/LPS22HB_Driver_HL.c \
C:/Users/Usuario/Desktop/COPIAS_SEGURIDAD/STM32CubeExpansion_MEMS1_V4.4.1/Drivers/BSP/Components/lps25hb/LPS25HB_Driver.c \
C:/Users/Usuario/Desktop/COPIAS_SEGURIDAD/STM32CubeExpansion_MEMS1_V4.4.1/Drivers/BSP/Components/lps25hb/LPS25HB_Driver_HL.c \
C:/Users/Usuario/Desktop/COPIAS_SEGURIDAD/STM32CubeExpansion_MEMS1_V4.4.1/Drivers/BSP/Components/lsm6ds0/LSM6DS0_ACC_GYRO_driver.c \
C:/Users/Usuario/Desktop/COPIAS_SEGURIDAD/STM32CubeExpansion_MEMS1_V4.4.1/Drivers/BSP/Components/lsm6ds0/LSM6DS0_ACC_GYRO_driver_HL.c \
C:/Users/Usuario/Desktop/COPIAS_SEGURIDAD/STM32CubeExpansion_MEMS1_V4.4.1/Drivers/BSP/Components/lsm6ds3/LSM6DS3_ACC_GYRO_driver.c \
C:/Users/Usuario/Desktop/COPIAS_SEGURIDAD/STM32CubeExpansion_MEMS1_V4.4.1/Drivers/BSP/Components/lsm6ds3/LSM6DS3_ACC_GYRO_driver_HL.c 

OBJS += \
./Drivers/BSP/Components/HTS221_Driver.o \
./Drivers/BSP/Components/HTS221_Driver_HL.o \
./Drivers/BSP/Components/LIS3MDL_MAG_driver.o \
./Drivers/BSP/Components/LIS3MDL_MAG_driver_HL.o \
./Drivers/BSP/Components/LPS22HB_Driver.o \
./Drivers/BSP/Components/LPS22HB_Driver_HL.o \
./Drivers/BSP/Components/LPS25HB_Driver.o \
./Drivers/BSP/Components/LPS25HB_Driver_HL.o \
./Drivers/BSP/Components/LSM6DS0_ACC_GYRO_driver.o \
./Drivers/BSP/Components/LSM6DS0_ACC_GYRO_driver_HL.o \
./Drivers/BSP/Components/LSM6DS3_ACC_GYRO_driver.o \
./Drivers/BSP/Components/LSM6DS3_ACC_GYRO_driver_HL.o 

C_DEPS += \
./Drivers/BSP/Components/HTS221_Driver.d \
./Drivers/BSP/Components/HTS221_Driver_HL.d \
./Drivers/BSP/Components/LIS3MDL_MAG_driver.d \
./Drivers/BSP/Components/LIS3MDL_MAG_driver_HL.d \
./Drivers/BSP/Components/LPS22HB_Driver.d \
./Drivers/BSP/Components/LPS22HB_Driver_HL.d \
./Drivers/BSP/Components/LPS25HB_Driver.d \
./Drivers/BSP/Components/LPS25HB_Driver_HL.d \
./Drivers/BSP/Components/LSM6DS0_ACC_GYRO_driver.d \
./Drivers/BSP/Components/LSM6DS0_ACC_GYRO_driver_HL.d \
./Drivers/BSP/Components/LSM6DS3_ACC_GYRO_driver.d \
./Drivers/BSP/Components/LSM6DS3_ACC_GYRO_driver_HL.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/BSP/Components/HTS221_Driver.o: C:/Users/Usuario/Desktop/COPIAS_SEGURIDAD/STM32CubeExpansion_MEMS1_V4.4.1/Drivers/BSP/Components/hts221/HTS221_Driver.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F401xE -DUSE_STM32F4XX_NUCLEO -c -I../../../../Inc -I../../../../../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../../../../../Drivers/BSP/STM32F4xx-Nucleo -I../../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../../Drivers/BSP/Components/lps25hb -I../../../../../../../../../Drivers/BSP/Components/lsm6ds0 -I../../../../../../../../../Drivers/BSP/Components/lsm6ds3 -I../../../../../../../../../Drivers/BSP/Components/lps22hb -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/BSP/Components/HTS221_Driver.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/HTS221_Driver_HL.o: C:/Users/Usuario/Desktop/COPIAS_SEGURIDAD/STM32CubeExpansion_MEMS1_V4.4.1/Drivers/BSP/Components/hts221/HTS221_Driver_HL.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F401xE -DUSE_STM32F4XX_NUCLEO -c -I../../../../Inc -I../../../../../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../../../../../Drivers/BSP/STM32F4xx-Nucleo -I../../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../../Drivers/BSP/Components/lps25hb -I../../../../../../../../../Drivers/BSP/Components/lsm6ds0 -I../../../../../../../../../Drivers/BSP/Components/lsm6ds3 -I../../../../../../../../../Drivers/BSP/Components/lps22hb -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/BSP/Components/HTS221_Driver_HL.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/LIS3MDL_MAG_driver.o: C:/Users/Usuario/Desktop/COPIAS_SEGURIDAD/STM32CubeExpansion_MEMS1_V4.4.1/Drivers/BSP/Components/lis3mdl/LIS3MDL_MAG_driver.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F401xE -DUSE_STM32F4XX_NUCLEO -c -I../../../../Inc -I../../../../../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../../../../../Drivers/BSP/STM32F4xx-Nucleo -I../../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../../Drivers/BSP/Components/lps25hb -I../../../../../../../../../Drivers/BSP/Components/lsm6ds0 -I../../../../../../../../../Drivers/BSP/Components/lsm6ds3 -I../../../../../../../../../Drivers/BSP/Components/lps22hb -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/BSP/Components/LIS3MDL_MAG_driver.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/LIS3MDL_MAG_driver_HL.o: C:/Users/Usuario/Desktop/COPIAS_SEGURIDAD/STM32CubeExpansion_MEMS1_V4.4.1/Drivers/BSP/Components/lis3mdl/LIS3MDL_MAG_driver_HL.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F401xE -DUSE_STM32F4XX_NUCLEO -c -I../../../../Inc -I../../../../../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../../../../../Drivers/BSP/STM32F4xx-Nucleo -I../../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../../Drivers/BSP/Components/lps25hb -I../../../../../../../../../Drivers/BSP/Components/lsm6ds0 -I../../../../../../../../../Drivers/BSP/Components/lsm6ds3 -I../../../../../../../../../Drivers/BSP/Components/lps22hb -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/BSP/Components/LIS3MDL_MAG_driver_HL.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/LPS22HB_Driver.o: C:/Users/Usuario/Desktop/COPIAS_SEGURIDAD/STM32CubeExpansion_MEMS1_V4.4.1/Drivers/BSP/Components/lps22hb/LPS22HB_Driver.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F401xE -DUSE_STM32F4XX_NUCLEO -c -I../../../../Inc -I../../../../../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../../../../../Drivers/BSP/STM32F4xx-Nucleo -I../../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../../Drivers/BSP/Components/lps25hb -I../../../../../../../../../Drivers/BSP/Components/lsm6ds0 -I../../../../../../../../../Drivers/BSP/Components/lsm6ds3 -I../../../../../../../../../Drivers/BSP/Components/lps22hb -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/BSP/Components/LPS22HB_Driver.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/LPS22HB_Driver_HL.o: C:/Users/Usuario/Desktop/COPIAS_SEGURIDAD/STM32CubeExpansion_MEMS1_V4.4.1/Drivers/BSP/Components/lps22hb/LPS22HB_Driver_HL.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F401xE -DUSE_STM32F4XX_NUCLEO -c -I../../../../Inc -I../../../../../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../../../../../Drivers/BSP/STM32F4xx-Nucleo -I../../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../../Drivers/BSP/Components/lps25hb -I../../../../../../../../../Drivers/BSP/Components/lsm6ds0 -I../../../../../../../../../Drivers/BSP/Components/lsm6ds3 -I../../../../../../../../../Drivers/BSP/Components/lps22hb -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/BSP/Components/LPS22HB_Driver_HL.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/LPS25HB_Driver.o: C:/Users/Usuario/Desktop/COPIAS_SEGURIDAD/STM32CubeExpansion_MEMS1_V4.4.1/Drivers/BSP/Components/lps25hb/LPS25HB_Driver.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F401xE -DUSE_STM32F4XX_NUCLEO -c -I../../../../Inc -I../../../../../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../../../../../Drivers/BSP/STM32F4xx-Nucleo -I../../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../../Drivers/BSP/Components/lps25hb -I../../../../../../../../../Drivers/BSP/Components/lsm6ds0 -I../../../../../../../../../Drivers/BSP/Components/lsm6ds3 -I../../../../../../../../../Drivers/BSP/Components/lps22hb -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/BSP/Components/LPS25HB_Driver.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/LPS25HB_Driver_HL.o: C:/Users/Usuario/Desktop/COPIAS_SEGURIDAD/STM32CubeExpansion_MEMS1_V4.4.1/Drivers/BSP/Components/lps25hb/LPS25HB_Driver_HL.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F401xE -DUSE_STM32F4XX_NUCLEO -c -I../../../../Inc -I../../../../../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../../../../../Drivers/BSP/STM32F4xx-Nucleo -I../../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../../Drivers/BSP/Components/lps25hb -I../../../../../../../../../Drivers/BSP/Components/lsm6ds0 -I../../../../../../../../../Drivers/BSP/Components/lsm6ds3 -I../../../../../../../../../Drivers/BSP/Components/lps22hb -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/BSP/Components/LPS25HB_Driver_HL.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/LSM6DS0_ACC_GYRO_driver.o: C:/Users/Usuario/Desktop/COPIAS_SEGURIDAD/STM32CubeExpansion_MEMS1_V4.4.1/Drivers/BSP/Components/lsm6ds0/LSM6DS0_ACC_GYRO_driver.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F401xE -DUSE_STM32F4XX_NUCLEO -c -I../../../../Inc -I../../../../../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../../../../../Drivers/BSP/STM32F4xx-Nucleo -I../../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../../Drivers/BSP/Components/lps25hb -I../../../../../../../../../Drivers/BSP/Components/lsm6ds0 -I../../../../../../../../../Drivers/BSP/Components/lsm6ds3 -I../../../../../../../../../Drivers/BSP/Components/lps22hb -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/BSP/Components/LSM6DS0_ACC_GYRO_driver.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/LSM6DS0_ACC_GYRO_driver_HL.o: C:/Users/Usuario/Desktop/COPIAS_SEGURIDAD/STM32CubeExpansion_MEMS1_V4.4.1/Drivers/BSP/Components/lsm6ds0/LSM6DS0_ACC_GYRO_driver_HL.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F401xE -DUSE_STM32F4XX_NUCLEO -c -I../../../../Inc -I../../../../../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../../../../../Drivers/BSP/STM32F4xx-Nucleo -I../../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../../Drivers/BSP/Components/lps25hb -I../../../../../../../../../Drivers/BSP/Components/lsm6ds0 -I../../../../../../../../../Drivers/BSP/Components/lsm6ds3 -I../../../../../../../../../Drivers/BSP/Components/lps22hb -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/BSP/Components/LSM6DS0_ACC_GYRO_driver_HL.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/LSM6DS3_ACC_GYRO_driver.o: C:/Users/Usuario/Desktop/COPIAS_SEGURIDAD/STM32CubeExpansion_MEMS1_V4.4.1/Drivers/BSP/Components/lsm6ds3/LSM6DS3_ACC_GYRO_driver.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F401xE -DUSE_STM32F4XX_NUCLEO -c -I../../../../Inc -I../../../../../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../../../../../Drivers/BSP/STM32F4xx-Nucleo -I../../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../../Drivers/BSP/Components/lps25hb -I../../../../../../../../../Drivers/BSP/Components/lsm6ds0 -I../../../../../../../../../Drivers/BSP/Components/lsm6ds3 -I../../../../../../../../../Drivers/BSP/Components/lps22hb -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/BSP/Components/LSM6DS3_ACC_GYRO_driver.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/Components/LSM6DS3_ACC_GYRO_driver_HL.o: C:/Users/Usuario/Desktop/COPIAS_SEGURIDAD/STM32CubeExpansion_MEMS1_V4.4.1/Drivers/BSP/Components/lsm6ds3/LSM6DS3_ACC_GYRO_driver_HL.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F401xE -DUSE_STM32F4XX_NUCLEO -c -I../../../../Inc -I../../../../../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../../../../../Drivers/BSP/STM32F4xx-Nucleo -I../../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../../../../Drivers/BSP/Components/lis3mdl -I../../../../../../../../../Drivers/BSP/Components/lps25hb -I../../../../../../../../../Drivers/BSP/Components/lsm6ds0 -I../../../../../../../../../Drivers/BSP/Components/lsm6ds3 -I../../../../../../../../../Drivers/BSP/Components/lps22hb -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/BSP/Components/LSM6DS3_ACC_GYRO_driver_HL.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

